<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-1QBSVOI" failures="2" tests="20" name="com.apex.api_Testcases.CustomerPOSTAPITestng" time="14.715" errors="0" timestamp="2022-08-02T18:09:25 PDT" skipped="0">
  <testcase classname="com.apex.api_Testcases.CustomerPOSTAPITestng" name="testWithGenderOnly" time="0.982"/>
  <system-out/>
  <testcase classname="com.apex.api_Testcases.CustomerPOSTAPITestng" name="testWithNameOnly" time="0.419"/>
  <system-out/>
  <testcase classname="com.apex.api_Testcases.CustomerPOSTAPITestng" name="testWithBlankGender" time="0.968"/>
  <system-out/>
  <testcase classname="com.apex.api_Testcases.CustomerPOSTAPITestng" name="testWithIncorrectGender" time="0.976"/>
  <system-out/>
  <testcase classname="com.apex.api_Testcases.CustomerPOSTAPITestng" name="testWithLengthyName" time="0.450"/>
  <system-out/>
  <testcase classname="com.apex.api_Testcases.CustomerPOSTAPITestng" name="testWithIncorrectStatus" time="0.964"/>
  <system-out/>
  <testcase classname="com.apex.api_Testcases.CustomerPOSTAPITestng" name="testWithMissingDomain" time="0.936"/>
  <system-out/>
  <testcase classname="com.apex.api_Testcases.CustomerPOSTAPITestng" name="testWithStatusOnly" time="0.417"/>
  <system-out/>
  <testcase classname="com.apex.api_Testcases.CustomerPOSTAPITestng" name="testWithMissingSymbol" time="0.949"/>
  <system-out/>
  <testcase classname="com.apex.api_Testcases.CustomerPOSTAPITestng" name="testWithBlankEmail" time="1.698"/>
  <system-out/>
  <testcase classname="com.apex.api_Testcases.CustomerPOSTAPITestng" name="testWithEmailOnly" time="0.962"/>
  <system-out/>
  <testcase classname="com.apex.api_Testcases.CustomerPOSTAPITestng" name="testWithExistingData" time="0.908"/>
  <system-out/>
  <testcase classname="com.apex.api_Testcases.CustomerPOSTAPITestng" name="testWithExistingEmail" time="0.910"/>
  <system-out/>
  <testcase classname="com.apex.api_Testcases.CustomerPOSTAPITestng" name="testWithSoftAssertions_incomplete" time="0.007">
    <failure message="The following asserts failed:
	expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at com.apex.api_Testcases.CustomerPOSTAPITestng.testWithSoftAssertions_incomplete(CustomerPOSTAPITestng.java:520)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testWithSoftAssertions_incomplete -->
  <system-out/>
  <testcase classname="com.apex.api_Testcases.CustomerPOSTAPITestng" name="testWithCorrectData" time="0.946"/>
  <system-out/>
  <testcase classname="com.apex.api_Testcases.CustomerPOSTAPITestng" name="testWithMultipleSymbol" time="0.397"/>
  <system-out/>
  <testcase classname="com.apex.api_Testcases.CustomerPOSTAPITestng" name="testWithLengthyEmail" time="0.448"/>
  <system-out/>
  <testcase classname="com.apex.api_Testcases.CustomerPOSTAPITestng" name="testWithBlankName" time="0.959"/>
  <system-out/>
  <testcase classname="com.apex.api_Testcases.CustomerPOSTAPITestng" name="testWith_incomplete" time="0.012">
    <failure message="The following asserts failed:
	expected [true] but found [false],
	expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [true] but found [false],
expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at com.apex.api_Testcases.CustomerPOSTAPITestng.testWith_incomplete(CustomerPOSTAPITestng.java:506)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testWith_incomplete -->
  <system-out/>
  <testcase classname="com.apex.api_Testcases.CustomerPOSTAPITestng" name="testWithBlankStatus" time="0.407"/>
  <system-out/>
</testsuite> <!-- com.apex.api_Testcases.CustomerPOSTAPITestng -->
